<?php

declare(strict_types=1);

namespace Modules\Payroll\Services;

use Illuminate\Http\Client\ConnectionException;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Request;
use Modules\Payroll\Contracts\ExchangeRateFetcherInterface;
use Modules\Payroll\App\Exceptions\ExchangeRateUnavailableException;

final class ApiExchangeRateFetcher implements ExchangeRateFetcherInterface
{
    /**
     * Fetch the latest currency exchange rates from the external provider.
     *
     * @param string $baseCurrency The base currency code (e.g., USD).
     * @return array<string, float> An associative array of currency rates.
     * @throws \Modules\Payroll\App\Exceptions\ExchangeRateUnavailableException
     */
    public function fetchLatestRates(string $baseCurrency): array
    {
        // Retrieve the correlation ID provided or generated by the middleware
        $tracingId = Request::header('X-Correlation-ID') ?? Request::header('X-Request-ID');

        try {
            $response = Http::timeout(
                (int) config('services.exchange_rate.timeout', 10)
            )
            ->withoutVerifying()
            ->withHeaders(array_filter([
                'X-Correlation-ID' => $tracingId, // Pass trace ID to the external API for distributed tracing
            ]))
            ->get(
                rtrim(
                    (string) config('services.exchange_rate.base_url'),
                    '/'
                ) . "/latest?from={$baseCurrency}"
            );
        } catch (ConnectionException $exception) {
            throw new ExchangeRateUnavailableException(
                fromCurrency: $baseCurrency,
                toCurrency: 'multiple',
            );
        }

        if ($response->failed()) {
            throw new ExchangeRateUnavailableException(
                fromCurrency: $baseCurrency,
                toCurrency: 'multiple',
            );
        }

        $rates = $response->json('rates');

        if (!is_array($rates)) {
            throw new ExchangeRateUnavailableException(
                fromCurrency: $baseCurrency,
                toCurrency: 'multiple',
            );
        }

        // Cast all rate values strictly to float
        return array_map(
            static fn ($rate): float => (float) $rate,
            $rates
        );
    }
}